/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GithubConnectRouteImport } from './routes/github-connect'
import { Route as IndexRouteImport } from './routes/index'

const GithubConnectRoute = GithubConnectRouteImport.update({
  id: '/github-connect',
  path: '/github-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/github-connect': typeof GithubConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/github-connect': typeof GithubConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/github-connect': typeof GithubConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/github-connect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/github-connect'
  id: '__root__' | '/' | '/github-connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubConnectRoute: typeof GithubConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/github-connect': {
      id: '/github-connect'
      path: '/github-connect'
      fullPath: '/github-connect'
      preLoaderRoute: typeof GithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubConnectRoute: GithubConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
